on:
  push:

jobs:
  continuos-integration:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Nodejs
      id: setup-node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Setup Typescript
      run: npm i
    - name: Compile Typescript
      run: tsc