on:
  push:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Setup typescript
      run: npm i
    - name: tsc
      uses: icrawl/action-tsc@v1